import type { RelicDefinition, RelicId } from "../model";
export const relics: Record<RelicId, RelicDefinition> = {
	tar: {
		id: "tar",
		title: "Смоляная бочка",
		description: "Масло держится в полтора раза дольше.",
		sprite: "tarRelic",
		rarity: "common",
	},
	bellows: {
		id: "bellows",
		title: "Мехи",
		description: "Горение наносит на треть больше урона.",
		sprite: "bellowsRelic",
		rarity: "common",
	},
	weight: {
		id: "weight",
		title: "Гиря",
		description: "Оглушение длится на секунду дольше.",
		sprite: "weightRelic",
		rarity: "common",
	},
	stacks: {
		id: "stacks",
		title: "Стаки горения",
		description: "Каждый поджог усиливает горение. До 3 стаков.",
		sprite: "stacksRelic",
		rarity: "common",
	},
	interest: {
		id: "interest",
		title: "Процент",
		description: "В конце волны +1 монета за каждые 5 в казне, до 200.",
		sprite: "interestRelic",
		rarity: "common",
	},
	whetstone: {
		id: "whetstone",
		title: "Точило",
		description: "Навсегда +0.5 урона за каждую построенную башню.",
		sprite: "whetstoneRelic",
		rarity: "common",
	},
	fowler: {
		id: "fowler",
		title: "Птицелов",
		description: "Каждый сбитый летун навсегда +1 урона стрелам.",
		sprite: "fowlerRelic",
		rarity: "common",
	},
	nomad: {
		id: "nomad",
		title: "Кочевник",
		description: "Перенос башни мгновенный, без повторной стройки.",
		sprite: "nomadRelic",
		rarity: "common",
	},
	echo: {
		id: "echo",
		title: "Эхо",
		description: "Каждый пятый выстрел башни срабатывает дважды.",
		sprite: "echoRelic",
		rarity: "rare",
	},
	piggy: {
		id: "piggy",
		title: "Свинья-копилка",
		description: "Копит по 3 монеты за волну. Выбросив её, забираешь всё.",
		sprite: "piggyRelic",
		rarity: "rare",
	},
	brand: {
		id: "brand",
		title: "Клеймо",
		description: "Враг, умерший оглушённым, навсегда +2 урона камнемётам.",
		sprite: "brandRelic",
		rarity: "rare",
	},
	rush: {
		id: "rush",
		title: "Аврал",
		description: "Башня готова сразу, но десять секунд бьёт вполсилы.",
		sprite: "rushRelic",
		rarity: "rare",
	},
	brigade: {
		id: "brigade",
		title: "Ударная бригада",
		description: "Башня, достроенная при врагах на дороге, навсегда быстрее.",
		sprite: "brigadeRelic",
		rarity: "rare",
	},
	autopsy: {
		id: "autopsy",
		title: "Вскрытие",
		description: "По щиту урон двойной, по врагу без щита — половинный.",
		sprite: "autopsyRelic",
		rarity: "rare",
	},
	behead: {
		id: "behead",
		title: "Обезглавливание",
		description: "Разрушение щита отряда бьёт по площади.",
		sprite: "beheadRelic",
		rarity: "rare",
	},
	outpost: {
		id: "outpost",
		title: "Аванпост",
		description: "Самая дальняя от базы башня бьёт вдвое.",
		sprite: "outpostRelic",
		rarity: "rare",
	},
	battery: {
		id: "battery",
		title: "Батарея",
		description: "Две башни одного типа рядом стреляют быстрее.",
		sprite: "batteryRelic",
		rarity: "rare",
	},
	vial: {
		id: "vial",
		title: "Хрупкий фиал",
		description: "Горение бьёт вдвое, но реликвия сгорает при первом прорыве.",
		sprite: "vialRelic",
		rarity: "rare",
	},
	greed: {
		id: "greed",
		title: "Жадность",
		description: "+1 урона за каждые 20 монет. Прорыв сжигает 20% казны.",
		sprite: "greedRelic",
		rarity: "key",
	},
	chain: {
		id: "chain",
		title: "Цепной поджог",
		description: "Горение переходит на промасленных соседей.",
		sprite: "chainRelic",
		rarity: "key",
	},
	blueprint: {
		id: "blueprint",
		title: "Чертёж",
		description: "Копирует эффект реликвии справа от себя.",
		sprite: "blueprintRelic",
		rarity: "key",
	},
	bones: {
		id: "bones",
		title: "Костяной страж",
		description: "Смертельный прорыв оставляет базе 1 HP, реликвия исчезает.",
		sprite: "bonesRelic",
		rarity: "key",
	},
	bridge: {
		id: "bridge",
		title: "Мост",
		description: "Камнемёт и масло начинают бить летунов.",
		sprite: "bridgeRelic",
		rarity: "key",
	},
	tinder: {
		id: "tinder",
		title: "Сухой трут",
		description: "Горение не гаснет. На пятидесятом поджоге станет «Пеплом».",
		sprite: "tinderRelic",
		rarity: "key",
	},
	ash: {
		id: "ash",
		title: "Пепел",
		description: "Огонь бьёт втрое. Остаётся от сгоревшего сухого трута.",
		sprite: "ashRelic",
		rarity: "key",
		offered: false,
	},
	mark: {
		id: "mark",
		title: "Метка",
		description: "Все башни бьют самую раненую цель.",
		sprite: "markRelic",
		rarity: "key",
	},
	lastStand: {
		id: "lastStand",
		title: "Последний рубеж",
		description: "Ближняя к базе башня бьёт тем сильнее, чем ниже здоровье.",
		sprite: "lastStandRelic",
		rarity: "key",
	},
};
export const rarityWeights = {
	common: (wave: number) => Math.max(1, 12 - wave),
	rare: (wave: number) => Math.min(8, 1 + wave / 2),
	key: (wave: number) => Math.max(0, (wave - 6) / 3),
} satisfies Record<RelicDefinition["rarity"], (wave: number) => number>;
export type { RelicId };
