import { colors } from "@/ui/colors";
import type { TowerKind } from "@/games/defense/definitions/towers";
import type { EnemyKind } from "@/games/defense/definitions/enemies";
export const defenseTheme = {
	towerCards: {
		rapid: "#352d17",
		blast: "#38201d",
		frost: "#132c3a",
		arcane: "#28213c",
	} satisfies Record<TowerKind, string>,
	towers: {
		rapid: colors.graphicWarningPrimary,
		blast: colors.graphicNegativePrimary,
		frost: colors.graphicActionPrimary,
		arcane: colors.graphicMarketing,
	} satisfies Record<TowerKind, string>,
	enemies: {
		normal: colors.textPrimary,
		fast: colors.graphicWarningPrimary,
		shield: colors.graphicActionPrimary,
		tank: colors.graphicAccentPrimary,
		wisp: colors.graphicMarketing,
		herald: colors.textPositive,
		boss: colors.graphicNegativePrimary,
	} satisfies Record<EnemyKind, string>,
	board: {
		buildAllowed: colors.textPositive,
		buildBlocked: colors.textNegative,
		background: colors.layerFloor1,
		cellAccent: colors.layerFloor3,
		cell: colors.layerFloor2,
		dot: colors.graphicQuaternary,
		road: colors.layerFloor0,
		roadMark: colors.graphicQuaternary,
		selection: colors.graphicActionPrimary,
		label: colors.textSecondary,
	},
	snow: {
		fill: colors.bgActionSecondary,
		edge: colors.graphicActionPrimary,
		flake: colors.textPrimary,
	},
	portal: {
		entrance: colors.graphicActionPrimary,
		spark: colors.textPrimary,
		link: colors.graphicMarketing,
		fill: colors.bgMarketingSecondarySolid,
		cooldown: colors.textTertiary,
		edge: colors.graphicMarketing,
		label: colors.textPrimary,
	},
	units: {
		rangeFill: colors.bgActionSecondary,
		rangeEdge: colors.graphicActionPrimary,
		shadow: colors.layerOverlayDimming,
		towerBody: colors.layerFloor1,
		shatter: colors.textPrimary,
		auraFill: colors.bgPositiveSecondary,
		auraEdge: colors.graphicPositivePrimary,
		enemyGlyph: colors.textPrimaryOnLight,
		teleported: colors.graphicMarketing,
		shield: colors.graphicActionPrimary,
		healthTrack: colors.layerFloor0,
		health: colors.textPositive,
		timer: colors.textPrimary,
		badge: colors.layerFloor1,
	},
	statuses: {
		cold: colors.graphicActionPrimary,
		armor: colors.graphicNegativePrimary,
		ward: colors.graphicMarketing,
		haste: colors.textPositive,
		echo: colors.graphicMarketing,
		chilledWeapon: colors.graphicActionPrimary,
		power: colors.graphicWarningPrimary,
	},
} as const;
